kcl-lang/modules

helloAH/kcl.mod, helloAH/main.k
=> test: this is a test for publishing pkg

helloworld/kcl.mod, helloworld/main.k
=> feat: add sample named helloworld

helloworld/kcl.mod, helloworld/main.k
=> fix: rm sample

helloworld/README.md, helloworld/kcl.mod, helloworld/main.k
=> publish package helloworld

helloworld/0.0.1/artifacthub-pkg.yaml, main.go
=> fix: add default value for package description

set-annotations/README.md, set-annotations/kcl.mod, set-annotations/main.k, set-annotations/suite/config.yaml, set-annotations/suite/good.yaml
feat: add set-annotations models
+ set-annotations/
=> feat: add set-annotations models

collectionutil/README.md, collectionutil/kcl.mod, collectionutil/main.k
feat: add collectionutil module v0.0.1
+ collectionutil/README.md
=> feat: add collectionutil module v0.0.1

.github/workflows/update_all_metadatas.yaml
=> feat: add workflow to supports manual republishing all kcl packages

.github/workflows/update_all_metadatas.yaml
=> fix: make republish into manual

README-zh.md, README.md
=> feat: add quick start in README.md

psp-allowed-users/kcl.mod, psp-allowed-users/main.k
refactor: enhance psp allowed users module and tag v0.1.1
+ psp-allowed-users/*
=> refactor: enhance psp allowed users module and tag v0.1.1

psp-volumes/README.md, psp-volumes/kcl.mod, psp-volumes/main.k
feat: add psp volume module
+ psp-volumes/main.k
=> feat: add psp volume module

.github/workflows/test.yaml, .github/workflows/update_metadata.yaml, .github/workflows/update_specified_metadatas.yaml, go.mod, go.sum, main.go, main_test.go
=> feat: add test case and the workflow 'Publish Specified Packages'

container_profile/README.md, container_profile/kcl.mod, container_profile/main.k, psp-seccomp/README.md, psp-seccomp/kcl.mod, psp-seccomp/main.k, psp-volumes/kcl.mod
=> feat: psp-seccomp module

psp-proc-mount/README.md, psp-proc-mount/kcl.mod, psp-proc-mount/main.k
=> feat: add psp proc mount

psp-host-network-ports/README.md, psp-host-network-ports/kcl.mod, psp-host-network-ports/main.k
=> feat: psp-host-network-ports

psp-host-namespaces/README.md, psp-host-namespaces/kcl.mod, psp-host-namespaces/main.k
feat: add psp-host-namespaces modules
=> feat: add psp-host-namespaces modules

psp-fsgroup/README.md, psp-fsgroup/kcl.mod, psp-fsgroup/main.k
=> feat: add psp fsgroup module

psp-forbidden-sysctls/README.md, psp-forbidden-sysctls/kcl.mod, psp-forbidden-sysctls/main.k
=> feat: add psp-forbidden-sysctls modules

semver/README.md, semver/kcl.mod, semver/main.k
feat: add semver module
+ semver/**
=> feat: add semver module

helloworld/artifacthub-pkg.yaml, helloworld/kcl.mod, main.go, main_test.go
=> feat: allow the custom artifacthub-pkg.yml

README-zh.md, README.md
=> feat: add more detailed information in README.md

.github/workflows/cla.yaml
=> ci: add cla check

.integration/artifacthub/karmada/0.1.0/artifacthub-pkg.yaml
=> fix: fix the metadata for package karmada

kcl_type/README.md, kcl_type/kcl.mod, kcl_type/main.k
feat: add kcl type modules
+ kcl_type/**
=> feat: add kcl type modules

jsonpatch/Makefile, jsonpatch/kcl.mod, jsonpatch/main.k
test: add unit tests for the jsonpatch module
+ jsonpatch/Makefile
+ jsonpatch/kcl.mod
+ jsonpatch/main.k
=> test: add unit tests for the jsonpatch module

argo-application-field-validation/kcl.mod, argo-application-prevent-default-project/README.md, argo-application-prevent-default-project/kcl.mod, argo-application-prevent-default-project/main.k, argo-applicationset-name-matches-project/README.md, argo-applicationset-name-matches-project/kcl.mod, argo-applicationset-name-matches-project/main.k, argo-appproject-clusterresourceblacklist/README.md, argo-appproject-clusterresourceblacklist/kcl.mod, argo-appproject-clusterresourceblacklist/main.k, argo-workflow/README.md, argo-workflow/kcl.mod
feat: add more argo application validation modules
=> feat: add more argo application validation modules

k8s_manifests_containers/kcl.mod, required-drop-all/README.md, required-drop-all/kcl.mod, required-drop-all/main.k, required-drop-cap-net-all/README.md, required-drop-cap-net-all/kcl.mod, required-drop-cap-net-all/main.k, required-pod-requests-limits/README.md, required-pod-requests-limits/kcl.mod, required-pod-requests-limits/main.k, required-root-fs/README.md, required-root-fs/kcl.mod, required-root-fs/main.k, restrict-image-registries/README.md, restrict-image-registries/kcl.mod, restrict-image-registries/main.k, restrict-service-external-ips/README.md, restrict-service-external-ips/kcl.mod, restrict-service-external-ips/main.k
feat: add more container validation modules
=> feat: add more container validation modules

check-auto-mount-service-account-token/README.md, check-auto-mount-service-account-token/kcl.mod, check-auto-mount-service-account-token/main.k, check-container-limits/README.md, check-container-limits/kcl.mod, check-container-limits/main.k, check-container-requests/README.md, check-container-requests/kcl.mod, check-container-requests/main.k, check-deprecated-api/README.md, check-deprecated-api/kcl.mod, check-deprecated-api/main.k, check-probes/README.md, check-probes/kcl.mod, check-probes/main.k
=> feat: add more check modules

README-zh.md, README.md
chore: bump modules repo and use kcl mod instead of kpm
+ README-zh.md
+ README.md
=> chore: bump modules repo and use kcl mod instead of kpm

add-network-policy-dns/kcl.mod, add-network-policy-dns/main.k, add-network-policy/kcl.mod, add-network-policy/main.k, add-rolebinding/kcl.mod, add-rolebinding/main.k, istio-add-sidecar-injection/README.md, istio-add-sidecar-injection/kcl.mod, istio-add-sidecar-injection/main.k, istio-check-mtls/README.md, istio-check-mtls/kcl.mod, istio-check-mtls/main.k, istio-check-sidecar-injection-label/README.md, istio-check-sidecar-injection-label/kcl.mod, istio-check-sidecar-injection-label/main.k, istio-check-virtual-service-wildcard/README.md, istio-check-virtual-service-wildcard/kcl.mod, istio-check-virtual-service-wildcard/main.k, istio-create-authorization-policy/README.md, istio-create-authorization-policy/kcl.mod, istio-create-authorization-policy/main.k, istio-enforce-tls-hosts-host-subnets/README.md, istio-enforce-tls-hosts-host-subnets/kcl.mod, istio-enforce-tls-hosts-host-subnets/main.k, istio-prevent-disabling-injection-pods/README.md, istio-prevent-disabling-injection-pods/kcl.mod, istio-prevent-disabling-injection-pods/main.k
feat: add more istio mutation and validation modules
=> feat: add more istio mutation and validation modules

nginx-ingress-restrict-annotations/README.md, nginx-ingress-restrict-annotations/kcl.mod, nginx-ingress-restrict-annotations/main.k, nginx-ingress-restrict-paths/README.md, nginx-ingress-restrict-paths/kcl.mod, nginx-ingress-restrict-paths/main.k
feat: add more nginx ingress modules
=> feat: add more nginx ingress modules

psp-check-supplemental-groups/README.md, psp-check-supplemental-groups/kcl.mod, psp-check-supplemental-groups/main.k
feat: add psp-check-supplemental-groups-modules
=> feat: add psp-check-supplemental-groups-modules

nginx-ingress-check-config-map/README.md, nginx-ingress-check-config-map/kcl.mod, nginx-ingress-check-config-map/main.k, nginx-ingress-disallow-custom-snippets/README.md, nginx-ingress-disallow-custom-snippets/kcl.mod, nginx-ingress-disallow-custom-snippets/main.k
feat: publish more nginx ingress modules
=> feat: publish more nginx ingress modules

.github/PULL_REQUEST_TEMPLATE.md
=> feat: add a new pr template for publish package

artifacthub-repo.yaml
=> feat: replace the verified repo to update the install cmd

json_merge_patch/README.md, json_merge_patch/kcl.mod, json_merge_patch/main.k, json_merge_patch/main_test.k, looper/README.md, looper/kcl.mod, looper/main.k, looper/main_test.k, update-image-tag/README.md, update-image-tag/kcl.mod, update-image-tag/main.k, update-image-tag/main_test.k
Publish modules
+ looper
+ json_merge_patch
- **HomePage**: kcl-lang
=> feat: add more modules about merge and loop

.github/workflows/update_metadata.yaml
=> chore: update artifact pkg commits and fix typos

crossplane-xnetwork-kcl-function/kcl.mod, crossplane-xnetwork-kcl-function/main.k
=> feat: add crossplane-xnetwork-kcl-function

crossplane-xnetwork-kcl-function/kcl.mod, crossplane-xnetwork-kcl-function/main.k
=> feat: upgrade crossplane kcl function to v0.0.2

kubeadm/1.29/artifacthub-pkg.yaml, kubeadm/1.29/kcl.mod, kubeadm/1.29/v1beta3/cluster_configuration.k, kubeadm/1.29/v1beta3/init_configuration.k, kubeadm/1.29/v1beta3/kubelet_configuration.k
- **Email**:
Add kubeadm mode. and this is the first PR, so this is not a complete module.
=> add kubeadm

kcl-abstraction-example/kcl.mod, kcl-abstraction-example/kubernetes_render.k, kcl-playground/kcl.mod, kcl-playground/main.k, web-service/kcl.mod, web-service/main.k
=> fix: loop variable in kcl v0.8

web-service/kcl.mod, web-service/main.k
=> chore: enhance web-service-module with default config

jsonschema/kcl.mod, jsonschema/ty.k, jsonschema/ty_test.k
=> chore: update the jsonschema module

.github/workflows/cla.yaml
=> Disable auto block pr option of contributor-assistant/github-action

.github/workflows/test.yaml, .github/workflows/update_metadata.yaml, .github/workflows/update_specified_metadatas.yaml
Let we see what happen when this PR is merged :) @Peefy 
- **Email**:
=> chore: update github action to v4.

argo-cd-order/README.md, argo-cd-order/kcl.mod, argo-cd-order/main.k
Remove sync-wave annotation for resources in "Sync" state
- **Email**: ryabin.ss@gmail.com
- **HomePage**: https://github.com/metacoma
=> Fix camelCase and add more sync states

json_merge_patch/kcl.mod, json_merge_patch/main.k
=> chore: bump json merge patch version to 0.1.1

argo-cd-order/kcl.mod, argo-cd-order/main.k
Skip empty (None) resources
- **Email**: ryabin.ss@gmail.com
- **HomePage**: https://github.com/metacoma
=> argo-cd-order 0.2.0

helloworld/kcl.mod
=> chore: bump helloworld version to 0.1.2 to test

jsonpatch/Makefile, jsonpatch/kcl.mod, jsonpatch/main.k, jsonpatch/main_test.k
+ refactor: jsonpatch module test and bump version to 0.0.3
=> refactor: jsonpatch module test and bump version to 0.0.3
